"""first

Revision ID: 52061ccfa385
Revises: aae5e6efadd3
Create Date: 2025-05-25 18:31:45.854663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52061ccfa385'
down_revision = 'aae5e6efadd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
